#include "NuSTM32_CLK.h"

#define BUS_AHB1	0x1
#define BUS_AHB2	0x2
#define BUS_AHB3	0x4
#define BUS_APB1	0x10
#define BUS_APB2	0x11

///////////////////

STM32407G_BUS NULL_BUS = {0, 0};

STM32407G_BUS NuGetRCCBus(uint16_t nPort)
{
	STM32407G_BUS RCCBus[] = 
	{
		NULL_BUS,
		{RCC_AHB1Periph_GPIOA, BUS_AHB1},
		{RCC_AHB1Periph_GPIOB, BUS_AHB1},
		{RCC_AHB1Periph_GPIOC, BUS_AHB1},
		{RCC_AHB1Periph_GPIOD, BUS_AHB1},
		{RCC_AHB1Periph_GPIOE, BUS_AHB1},
		{RCC_AHB1Periph_GPIOF, BUS_AHB1},
		{RCC_AHB1Periph_GPIOG, BUS_AHB1},
		{RCC_AHB1Periph_GPIOH, BUS_AHB1},
		{RCC_AHB1Periph_GPIOI, BUS_AHB1},
		{RCC_AHB1Periph_GPIOJ, BUS_AHB1},
		{RCC_AHB1Periph_GPIOK, BUS_AHB1}, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, 
		NULL_BUS,//0x10
		{RCC_APB2Periph_TIM1, BUS_APB2},
		{RCC_APB1Periph_TIM2, BUS_APB1},
		{RCC_APB1Periph_TIM3, BUS_APB1},
		{RCC_APB1Periph_TIM4, BUS_APB1},
		{RCC_APB1Periph_TIM5, BUS_APB1},
		{RCC_APB1Periph_TIM6, BUS_APB1},
		{RCC_APB1Periph_TIM7, BUS_APB1},
		{RCC_APB2Periph_TIM8, BUS_APB2},
		{RCC_APB2Periph_TIM9, BUS_APB2},
		{RCC_APB2Periph_TIM10, BUS_APB2},
		{RCC_APB2Periph_TIM11, BUS_APB2},
		{RCC_APB1Periph_TIM12, BUS_APB1},
		{RCC_APB1Periph_TIM13, BUS_APB1},
		{RCC_APB1Periph_TIM14, BUS_APB1}, NULL_BUS, 
		NULL_BUS, //0x20
		{RCC_AHB1Periph_DMA1, BUS_AHB1}, 
		{RCC_AHB1Periph_DMA2, BUS_AHB1}, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, 
		NULL_BUS, //0x30
		{RCC_APB2Periph_ADC1, BUS_APB2}, 
		{RCC_APB2Periph_ADC2, BUS_APB2}, 
		{RCC_APB2Periph_ADC3, BUS_APB2}, 
		{RCC_APB1Periph_DAC, BUS_APB1}, 
		{RCC_APB1Periph_DAC, BUS_APB1}, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, 
		NULL_BUS, //0x40
		NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, 
		{RCC_APB1Periph_CAN1, BUS_APB1}, // 0x50
		{RCC_APB1Periph_CAN2, BUS_APB1}, 
		NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, 
		{RCC_APB2Periph_USART1, BUS_APB2}, // 0x60
		{RCC_APB1Periph_USART2, BUS_APB1}, 
		{RCC_APB1Periph_USART3, BUS_APB1},
		{RCC_APB2Periph_USART1, BUS_APB2},
		{RCC_APB1Periph_USART2, BUS_APB1},
		{RCC_APB1Periph_USART3, BUS_APB1},
		{RCC_APB2Periph_USART1, BUS_APB2},
		NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, NULL_BUS, 

	};
	return RCCBus[nPort];
}

void NuEnableRCCClock(uint16_t nPort)
{
	STM32407G_BUS stm32bus = NuGetRCCBus(nPort);
	switch (stm32bus.bus)
	{
		case BUS_AHB1:
			RCC_AHB1PeriphClockCmd(stm32bus.clock, ENABLE);
			break;
		case BUS_AHB2:
			RCC_AHB2PeriphClockCmd(stm32bus.clock, ENABLE);
			break;
		case BUS_AHB3:
			RCC_AHB3PeriphClockCmd(stm32bus.clock, ENABLE);
			break;
		case BUS_APB1:
			RCC_APB1PeriphClockCmd(stm32bus.clock, ENABLE);
			break;
		case BUS_APB2:
			RCC_APB2PeriphClockCmd(stm32bus.clock, ENABLE);
			break;
	}
}
